### ISSUE TITLE
Anti aliasing

### ISSUE THREAD

**Issue by rickyok** [bebensiganteng/Simple-PHP-Circular-Image-Crop#1]
dear beben,

i'm trying to make anti alias png circle cropping. From i known. there's now known method using GD to use anti alias. You have any idea how to do that?

**Comment by bebensiganteng** [comment]
It has been awhile since I tinkered with PHP, because now a days there are a lot of good alternatives for image manipulation, what sort of platform are you aiming for (web/mobile/desktop/etc.)? incidentally perhaps you could look at this http://www.php.net/manual/en/function.imageantialias.php,

**Comment by saqueib** [comment]
Hi Beben, 

I am also facing same with the cracky corners due to Anti aliasing. 
I have search everywhere i cant find any script, if you can improve its crop function that will be awesome.

Here is the a library you can use, its make Anti aliasing possible using GD library 
http://www.ulrichmierendorff.com/software/antialiased_arcs.html

Thanks man for great work

**Comment by bebensiganteng** [comment]
Hi Saqueib, thanks for the kind words :+1: 

I honestly have never used PHP anymore for image manipulation (now a days I just use canvas/webgl)

But really, is the edge jagged? I thought I've solved that a long time ago.
